<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * "Actor / Director",
      "Artist",
      "Athlete",
      "Author",
      "Band",
      "Blogger",
      "Chef",
      "Comedian",
      "Dancer",
      "Designer",
      "Digital Creator",
      "Editor",
      "Entrepreneur / Business Person",
      "Fashion Designer / Model",
      "Film Director",
      "Fitness Model",
      "Gamer / Gaming Video Creator",
      "Journalist",
      "Motivational Speaker",
      "Musician / Band",
      "News Personality",
      "Orchestra",
      "Pet",
      "Photographer",
      "Producer",
      "Scientist / Spiritual Leader",
      "Sports Promoter / Sportsperson / Coach",
      "Teacher",
      "Video Creator",
      "Writer / Author",
      "Politician / Government Official / Political Candidate",
      "Entertainer",
      "Public Figure"

     */
    public function run(): void
    {
        $categories = [
            [
                'name' => 'Actor / Director',
                'slug' => 'actor-director',
                'icon' => 'fas fa-laptop',
                'description' => 'Actor / Director related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Artist',
                'slug' => 'artist',
                'icon' => 'fas fa-laptop',
                'description' => 'Artist related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Athlete',
                'slug' => 'athlete',
                'icon' => 'fas fa-laptop',
                'description' => 'Athlete related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Author',
                'slug' => 'author',
                'icon' => 'fas fa-laptop',
                'description' => 'Author related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Band',
                'slug' => 'band',
                'icon' => 'fas fa-laptop',
                'description' => 'Band related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blogger',
                'slug' => 'blogger',
                'icon' => 'fas fa-laptop',
                'description' => 'Blogger related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],  
            [
                'name' => 'Chef',
                'slug' => 'chef',
                'icon' => 'fas fa-laptop',
                'description' => 'Chef related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Comedian',
                'slug' => 'comedian',
                'icon' => 'fas fa-laptop',
                'description' => 'Comedian related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dancer',
                'slug' => 'dancer',
                'icon' => 'fas fa-laptop',
                'description' => 'Dancer related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Designer',
                'slug' => 'designer',
                'icon' => 'fas fa-laptop',
                'description' => 'Designer related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Digital Creator',
                'slug' => 'digital-creator',
                'icon' => 'fas fa-laptop',
                'description' => 'Digital Creator related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Editor',
                'slug' => 'editor',
                'icon' => 'fas fa-laptop',
                'description' => 'Editor related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Entrepreneur / Business Person',
                'slug' => 'entrepreneur-business-person',
                'icon' => 'fas fa-laptop',
                'description' => 'Entrepreneur / Business Person related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fashion Designer / Model',
                'slug' => 'fashion-designer-model',
                'icon' => 'fas fa-laptop',
                'description' => 'Fashion Designer / Model related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Film Director',
                'slug' => 'film-director',
                'icon' => 'fas fa-laptop',
                'description' => 'Film Director related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fitness Model',
                'slug' => 'fitness-model',
                'icon' => 'fas fa-laptop',
                'description' => 'Fitness Model related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gamer / Gaming Video Creator',
                'slug' => 'gamer-gaming-video-creator',
                'icon' => 'fas fa-laptop',
                'description' => 'Gamer / Gaming Video Creator related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Journalist',
                'slug' => 'journalist',
                'icon' => 'fas fa-laptop',
                'description' => 'Journalist related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Motivational Speaker',
                'slug' => 'motivational-speaker',
                'icon' => 'fas fa-laptop',
                'description' => 'Motivational Speaker related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Musician / Band',
                'slug' => 'musician-band',
                'icon' => 'fas fa-laptop',
                'description' => 'Musician / Band related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'News Personality',
                'slug' => 'news-personality',
                'icon' => 'fas fa-laptop',
                'description' => 'News Personality related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Orchestra',
                'slug' => 'orchestra',
                'icon' => 'fas fa-laptop',
                'description' => 'Orchestra related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pet',
                'slug' => 'pet',
                'icon' => 'fas fa-laptop',
                'description' => 'Pet related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Photographer',
                'slug' => 'photographer',
                'icon' => 'fas fa-laptop',
                'description' => 'Photographer related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Producer',
                'slug' => 'producer',
                'icon' => 'fas fa-laptop',
                'description' => 'Producer related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Scientist / Spiritual Leader',
                'slug' => 'scientist-spiritual-leader',
                'icon' => 'fas fa-laptop',
                'description' => 'Scientist / Spiritual Leader related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sports Promoter / Sportsperson / Coach',
                'slug' => 'sports-promoter-sportsperson-coach',
                'icon' => 'fas fa-laptop',
                'description' => 'Sports Promoter / Sportsperson / Coach related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teacher',
                'slug' => 'teacher',
                'icon' => 'fas fa-laptop',
                'description' => 'Teacher related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Video Creator',
                'slug' => 'video-creator',
                'icon' => 'fas fa-laptop',
                'description' => 'Video Creator related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Writer / Author',
                'slug' => 'writer-author',
                'icon' => 'fas fa-laptop',
                'description' => 'Writer / Author related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Politician / Government Official / Political Candidate',
                'slug' => 'politician-government-official-political-candidate',
                'icon' => 'fas fa-laptop',
                'description' => 'Politician / Government Official / Political Candidate related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Entertainer',
                'slug' => 'entertainer',
                'icon' => 'fas fa-laptop',
                'description' => 'Entertainer related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Public Figure',
                'slug' => 'public-figure',
                'icon' => 'fas fa-laptop',
                'description' => 'Public Figure related categories and discussions',
                'parent_id' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert categories into the database
        DB::table('categories')->insert($categories);
    }
}
